name: build & test
on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Gradle build (and test)
        run: ./gradlew build -x :metadata-ingestion:build -x :metadata-ingestion:check -x docs-website:build -x test
      - name: Archive binaries
        run: tar -czvf binaries.tgz */build
      - uses: actions/upload-artifact@v2
        with:
          name: "Binaries"
          path: binaries.tgz
          retention-days: 5

  test:
    name: "test (#${{ matrix.high-digit}}${{ matrix.low-digit}})"
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        high-digit: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        low-digit: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Binaries
          path: .
      - run: tar -xzvf binaries.tgz && rm -f binaries.tgz
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Gradle test metadata-io
        run: ./gradlew :metadata-io:test -x :metadata-ingestion:build -x :metadata-ingestion:check -x docs-website:build
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: "Test Results #${{ matrix.high-digit}}${{ matrix.low-digit}}"
          path: "**/build/reports/tests/test/**"
          retention-days: 5
      - name: Ensure codegen is updated
        run: |
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            # See https://unix.stackexchange.com/a/155077/378179.
            echo 'There are uncommitted changes:'
            echo $output
            exit 1
          else
            echo 'All good!'
          fi
      - name: Slack failure notification
        if: failure() && github.event_name == 'push'
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: github-activities

  metadata-ingestion-general:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Run metadata-ingestion tests
        run: ./gradlew :metadata-ingestion:build :metadata-ingestion:check

  metadata-ingestion-by-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh && python -m pip install --upgrade pip && pip install tox tox-gh-actions
      - name: Codegen
        run: ./gradlew :metadata-ingestion:codegen
      - name: Run tox tests
        run: cd metadata-ingestion && tox

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Gradle build
        run: ./gradlew build -x check -x docs-website:build
      - name: Smoke test
        run: ./smoke-test/smoke.sh
      - name: Slack failure notification
        if: failure() && github.event_name == 'push'
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: github-activities

  quickstart-compose-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Quickstart Compose Validation
        run: ./docker/quickstart/generate_and_compare.sh
